packages:
  - packages/*
catalog:
  vue: ^3.5
  lexical: 0.23.1
  "@lexical/utils": 0.23.1
  "@lexical/text": 0.23.1
  "@lexical/clipboard": 0.23.1
  "@lexical/html": 0.23.1
  "@lexical/history": 0.23.1
  "@lexical/devtools-core": 0.23.1
  "@lexical/selection": 0.23.1
  "@vanilla-extract/css": ^1.17
  "@vanilla-extract/recipes": ^0.5.5
  "@vanilla-extract/dynamic": ^2.1
